export const data = [
  {
    id: 1,
    investorName: "EMERAM Capital Partners",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Munich",
    founded: 2012,
    icon: "https://dummyimage.com/32x32/3498db/fff&text=E",
  },
  {
    id: 2,
    investorName: "CMP Capital Management Partners",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Berlin",
    founded: 2000,
    icon: "https://dummyimage.com/32x32/e74c3c/fff&text=C",
  },
  {
    id: 3,
    investorName: "Elvaston Capital Management",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Berlin",
    founded: 2050,
    icon: "https://dummyimage.com/32x32/2ecc71/fff&text=E",
  },
  {
    id: 4,
    investorName: "Lea Partners",
    type: "Fund Manager",
    asset: "Private Equity, Venture Capital",
    strategy: "Buyout, Growth",
    country: "Germany",
    city: "Karlsruhe",
    founded: 2002,
    icon: "https://dummyimage.com/32x32/9b59b6/fff&text=L",
  },
  {
    id: 5,
    investorName: "Main Capital Partners",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Netherlands",
    city: "The Hague",
    founded: 2003,
    icon: "https://dummyimage.com/32x32/f1c40f/000&text=M",
  },
  {
    id: 6,
    investorName: "Deutsche Beteiligungs AG",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Frankfurt Am Main",
    founded: 1965,
    icon: "https://dummyimage.com/32x32/1abc9c/fff&text=D",
  },
  {
    id: 7,
    investorName: "DPE Deutsche Private Equity GmbH",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Munich",
    founded: 2007,
    icon: "https://dummyimage.com/32x32/e67e22/fff&text=D",
  },
  {
    id: 8,
    investorName: "Wise Equity",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Italy",
    city: "Milano",
    founded: 2000,
    icon: "https://dummyimage.com/32x32/34495e/fff&text=W",
  },
  {
    id: 9,
    investorName: "Miura Partners",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Spain",
    city: "Barcelona",
    founded: 2008,
    icon: "https://dummyimage.com/32x32/16a085/fff&text=M",
  },
  {
    id: 10,
    investorName: "Xenon Private Equity",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Luxembourg",
    city: "Strassen",
    founded: 1446,
    icon: "https://dummyimage.com/32x32/8e44ad/fff&text=X",
  },
  {
    id: 11,
    investorName: "Aksia SGR",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Italy",
    city: "Milano",
    founded: 1997,
    icon: "https://dummyimage.com/32x32/d35400/fff&text=A",
  },
  {
    id: 12,
    investorName: "Investindustrial",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "United Kingdom",
    city: "London",
    founded: 1990,
    icon: "https://dummyimage.com/32x32/27ae60/fff&text=I",
  },
];
