export const data = [
  {
    id: 1,
    investorName: "EMERAM Capital Partners",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Munich",
    founded: 2012,
  },
  {
    id: 2,
    investorName: "CMP Capital Management Partners",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Berlin",
    founded: 2000,
  },
  {
    id: 3,
    investorName: "Elvaston Capital Management",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Berlin",
    founded: 2050,
  },
  {
    id: 4,
    investorName: "Lea Partners",
    type: "Fund Manager",
    asset: "Private Equity, Venture Capital",
    strategy: "Buyout, Growth",
    country: "Germany",
    city: "Karlsruhe",
    founded: 2002,
  },
  {
    id: 5,
    investorName: "Main Capital Partners",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Netherlands",
    city: "The Hague",
    founded: 2003,
  },
  {
    id: 6,
    investorName: "Deutsche Beteiligungs AG",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Frankfurt Am Main",
    founded: 1965,
  },
  {
    id: 7,
    investorName: "DPE Deutsche Private Equity GmbH",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Germany",
    city: "Munich",
    founded: 2007,
  },
  {
    id: 8,
    investorName: "Wise Equity",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Italy",
    city: "Milano",
    founded: 2000,
  },
  {
    id: 9,
    investorName: "Miura Partners",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Spain",
    city: "Barcelona",
    founded: 2008,
  },
  {
    id: 10,
    investorName: "Xenon Private Equity",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Luxembourg",
    city: "Strassen",
    founded: 1446,
  },
  {
    id: 11,
    investorName: "Aksia SGR",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "Italy",
    city: "Milano",
    founded: 1997,
  },
  {
    id: 12,
    investorName: "Investindustrial",
    type: "Fund Manager",
    asset: "Private Equity",
    strategy: "Buyout",
    country: "United Kingdom",
    city: "London",
    founded: 1990,
  },
];
